### ISSUE TITLE
Add ModSide to manifest.

### ISSUE THREAD

**Issue by Claycorp** [killjoy1221/tabbychat#18]
Adding 

```
manifest {
        attributes 'ModSide': 'CLIENT'
    }
```

to jar in your build.gradle file will mark the mod as client side and will prevent it from loading on server and thus crashing them.

**Comment by mattmess1221** [comment]
This is in tabbychat 2. I don't plan on doing anything more on this repo and I'm not going to make another release just for a manifest entry.
