### ISSUE TITLE
Jittery chat window?

### ISSUE THREAD

**Issue by evertiro** [killjoy1221/tabbychat#22]
Whenever I type more than 18 characters in the input area, the main chat window starts 'jittering'... it shifts between the standard position and a position roughly the height of the input bar higher until I stop typing.

**Comment by mattmess1221** [comment]
Assuming this is for TabbyChat 2 and wrong repo. Have you used the latest
development build?

**Comment by evertiro** [comment]
yes this is for 2, sorry. And no... the latest download I'd found was beta 3.1

**Comment by mattmess1221** [comment]
http://drone.io/github.com/killjoy1221/tabbychat-2/files

**Comment by mattmess1221** [comment]
If you still have this issue using latest, create a new issue in the proper repo.
